#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kio
Version  : 5.55.0
Release  : 17
URL      : https://download.kde.org/stable/frameworks/5.55/kio-5.55.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.55/kio-5.55.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.55/kio-5.55.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: kio-bin = %{version}-%{release}
Requires: kio-data = %{version}-%{release}
Requires: kio-lib = %{version}-%{release}
Requires: kio-license = %{version}-%{release}
Requires: kio-locales = %{version}-%{release}
Requires: kio-man = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : karchive-dev
BuildRequires : kbookmarks-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfig
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdoctools-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knotifications-dev
BuildRequires : krb5-dev
BuildRequires : kservice-dev
BuildRequires : kwallet-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kxmlgui-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : openssl-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : zlib-dev

%description
Proxy Auto Configuration is a means to use a JavaScript function to
determine the proxy to use based on the requested URL.
It is described in detail here:
http://home.netscape.com/eng/mozilla/2.0/relnotes/demo/proxy-live.html

%package bin
Summary: bin components for the kio package.
Group: Binaries
Requires: kio-data = %{version}-%{release}
Requires: kio-license = %{version}-%{release}
Requires: kio-man = %{version}-%{release}

%description bin
bin components for the kio package.


%package data
Summary: data components for the kio package.
Group: Data

%description data
data components for the kio package.


%package dev
Summary: dev components for the kio package.
Group: Development
Requires: kio-lib = %{version}-%{release}
Requires: kio-bin = %{version}-%{release}
Requires: kio-data = %{version}-%{release}
Provides: kio-devel = %{version}-%{release}

%description dev
dev components for the kio package.


%package doc
Summary: doc components for the kio package.
Group: Documentation
Requires: kio-man = %{version}-%{release}

%description doc
doc components for the kio package.


%package lib
Summary: lib components for the kio package.
Group: Libraries
Requires: kio-data = %{version}-%{release}
Requires: kio-license = %{version}-%{release}

%description lib
lib components for the kio package.


%package license
Summary: license components for the kio package.
Group: Default

%description license
license components for the kio package.


%package locales
Summary: locales components for the kio package.
Group: Default

%description locales
locales components for the kio package.


%package man
Summary: man components for the kio package.
Group: Default

%description man
man components for the kio package.


%prep
%setup -q -n kio-5.55.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549761125
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1549761125
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kio
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kio/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang kio5

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/kf5/kio_http_cache_cleaner
/usr/lib64/libexec/kf5/kiod5
/usr/lib64/libexec/kf5/kioexec
/usr/lib64/libexec/kf5/kioslave
/usr/lib64/libexec/kf5/kpac_dhcp_helper

%files bin
%defattr(-,root,root,-)
/usr/bin/kcookiejar5
/usr/bin/ktelnetservice5
/usr/bin/ktrash5
/usr/bin/protocoltojson

%files data
%defattr(-,root,root,-)
/usr/share/applications/ktelnetservice5.desktop
/usr/share/dbus-1/interfaces/kf5_org.kde.KCookieServer.xml
/usr/share/dbus-1/interfaces/kf5_org.kde.KDirNotify.xml
/usr/share/dbus-1/interfaces/kf5_org.kde.KPasswdServer.xml
/usr/share/dbus-1/interfaces/kf5_org.kde.KSlaveLauncher.xml
/usr/share/dbus-1/interfaces/kf5_org.kde.kio.FileUndoManager.xml
/usr/share/dbus-1/services/org.kde.kcookiejar5.service
/usr/share/dbus-1/services/org.kde.kiod5.service
/usr/share/dbus-1/services/org.kde.kioexecd.service
/usr/share/dbus-1/services/org.kde.kpasswdserver.service
/usr/share/dbus-1/services/org.kde.kssld5.service
/usr/share/kconf_update/filepicker.upd
/usr/share/kf5/kcookiejar/domain_info
/usr/share/knotifications5/proxyscout.notifyrc
/usr/share/kservices5/cache.desktop
/usr/share/kservices5/cookies.desktop
/usr/share/kservices5/data.protocol
/usr/share/kservices5/http_cache_cleaner.desktop
/usr/share/kservices5/kcmtrash.desktop
/usr/share/kservices5/mms.protocol
/usr/share/kservices5/mmst.protocol
/usr/share/kservices5/mmsu.protocol
/usr/share/kservices5/netpref.desktop
/usr/share/kservices5/pnm.protocol
/usr/share/kservices5/proxy.desktop
/usr/share/kservices5/rtsp.protocol
/usr/share/kservices5/rtspt.protocol
/usr/share/kservices5/rtspu.protocol
/usr/share/kservices5/searchproviders/7digital.desktop
/usr/share/kservices5/searchproviders/acronym.desktop
/usr/share/kservices5/searchproviders/amazon.desktop
/usr/share/kservices5/searchproviders/amazon_mp3.desktop
/usr/share/kservices5/searchproviders/amg.desktop
/usr/share/kservices5/searchproviders/archpkg.desktop
/usr/share/kservices5/searchproviders/backports.desktop
/usr/share/kservices5/searchproviders/baidu.desktop
/usr/share/kservices5/searchproviders/beolingus.desktop
/usr/share/kservices5/searchproviders/bing.desktop
/usr/share/kservices5/searchproviders/bugft.desktop
/usr/share/kservices5/searchproviders/bugno.desktop
/usr/share/kservices5/searchproviders/call.desktop
/usr/share/kservices5/searchproviders/cia.desktop
/usr/share/kservices5/searchproviders/citeseer.desktop
/usr/share/kservices5/searchproviders/cpan.desktop
/usr/share/kservices5/searchproviders/ctan.desktop
/usr/share/kservices5/searchproviders/ctan_cat.desktop
/usr/share/kservices5/searchproviders/dbug.desktop
/usr/share/kservices5/searchproviders/de2en.desktop
/usr/share/kservices5/searchproviders/de2fr.desktop
/usr/share/kservices5/searchproviders/deb.desktop
/usr/share/kservices5/searchproviders/dictfr.desktop
/usr/share/kservices5/searchproviders/docbook.desktop
/usr/share/kservices5/searchproviders/doi.desktop
/usr/share/kservices5/searchproviders/duckduckgo.desktop
/usr/share/kservices5/searchproviders/duckduckgo_info.desktop
/usr/share/kservices5/searchproviders/duckduckgo_shopping.desktop
/usr/share/kservices5/searchproviders/ecosia.desktop
/usr/share/kservices5/searchproviders/en2de.desktop
/usr/share/kservices5/searchproviders/en2es.desktop
/usr/share/kservices5/searchproviders/en2fr.desktop
/usr/share/kservices5/searchproviders/en2it.desktop
/usr/share/kservices5/searchproviders/es2en.desktop
/usr/share/kservices5/searchproviders/facebook.desktop
/usr/share/kservices5/searchproviders/feedster.desktop
/usr/share/kservices5/searchproviders/flickr.desktop
/usr/share/kservices5/searchproviders/flickrcc.desktop
/usr/share/kservices5/searchproviders/foldoc.desktop
/usr/share/kservices5/searchproviders/fr2de.desktop
/usr/share/kservices5/searchproviders/fr2en.desktop
/usr/share/kservices5/searchproviders/freecode.desktop
/usr/share/kservices5/searchproviders/freedb.desktop
/usr/share/kservices5/searchproviders/fsd.desktop
/usr/share/kservices5/searchproviders/github.desktop
/usr/share/kservices5/searchproviders/gitlab.desktop
/usr/share/kservices5/searchproviders/google.desktop
/usr/share/kservices5/searchproviders/google_advanced.desktop
/usr/share/kservices5/searchproviders/google_code.desktop
/usr/share/kservices5/searchproviders/google_groups.desktop
/usr/share/kservices5/searchproviders/google_images.desktop
/usr/share/kservices5/searchproviders/google_lucky.desktop
/usr/share/kservices5/searchproviders/google_maps.desktop
/usr/share/kservices5/searchproviders/google_movie.desktop
/usr/share/kservices5/searchproviders/google_news.desktop
/usr/share/kservices5/searchproviders/google_shopping.desktop
/usr/share/kservices5/searchproviders/grec.desktop
/usr/share/kservices5/searchproviders/hyperdictionary.desktop
/usr/share/kservices5/searchproviders/hyperdictionary_thesaurus.desktop
/usr/share/kservices5/searchproviders/identica_groups.desktop
/usr/share/kservices5/searchproviders/identica_notices.desktop
/usr/share/kservices5/searchproviders/identica_people.desktop
/usr/share/kservices5/searchproviders/imdb.desktop
/usr/share/kservices5/searchproviders/it2en.desktop
/usr/share/kservices5/searchproviders/jamendo.desktop
/usr/share/kservices5/searchproviders/jeeves.desktop
/usr/share/kservices5/searchproviders/kde.desktop
/usr/share/kservices5/searchproviders/kde_apps.desktop
/usr/share/kservices5/searchproviders/kde_forums.desktop
/usr/share/kservices5/searchproviders/kde_look.desktop
/usr/share/kservices5/searchproviders/kde_techbase.desktop
/usr/share/kservices5/searchproviders/kde_userbase.desktop
/usr/share/kservices5/searchproviders/leo.desktop
/usr/share/kservices5/searchproviders/magnatune.desktop
/usr/share/kservices5/searchproviders/metacrawler.desktop
/usr/share/kservices5/searchproviders/msdn.desktop
/usr/share/kservices5/searchproviders/multitran-deru.desktop
/usr/share/kservices5/searchproviders/multitran-enru.desktop
/usr/share/kservices5/searchproviders/multitran-esru.desktop
/usr/share/kservices5/searchproviders/multitran-frru.desktop
/usr/share/kservices5/searchproviders/multitran-itru.desktop
/usr/share/kservices5/searchproviders/multitran-nlru.desktop
/usr/share/kservices5/searchproviders/netcraft.desktop
/usr/share/kservices5/searchproviders/nl-telephone.desktop
/usr/share/kservices5/searchproviders/nl-teletekst.desktop
/usr/share/kservices5/searchproviders/opendesktop.desktop
/usr/share/kservices5/searchproviders/pgpkeys.desktop
/usr/share/kservices5/searchproviders/php.desktop
/usr/share/kservices5/searchproviders/python.desktop
/usr/share/kservices5/searchproviders/qt.desktop
/usr/share/kservices5/searchproviders/qt4.desktop
/usr/share/kservices5/searchproviders/qwant.desktop
/usr/share/kservices5/searchproviders/qwant_images.desktop
/usr/share/kservices5/searchproviders/qwant_news.desktop
/usr/share/kservices5/searchproviders/qwant_shopping.desktop
/usr/share/kservices5/searchproviders/qwant_social.desktop
/usr/share/kservices5/searchproviders/qwant_videos.desktop
/usr/share/kservices5/searchproviders/rae.desktop
/usr/share/kservices5/searchproviders/rag.desktop
/usr/share/kservices5/searchproviders/rfc.desktop
/usr/share/kservices5/searchproviders/rpmfind.desktop
/usr/share/kservices5/searchproviders/ruby_application_archive.desktop
/usr/share/kservices5/searchproviders/soundcloud.desktop
/usr/share/kservices5/searchproviders/sourceforge.desktop
/usr/share/kservices5/searchproviders/technorati.desktop
/usr/share/kservices5/searchproviders/technoratitags.desktop
/usr/share/kservices5/searchproviders/thesaurus.desktop
/usr/share/kservices5/searchproviders/tvtome.desktop
/usr/share/kservices5/searchproviders/urbandictionary.desktop
/usr/share/kservices5/searchproviders/uspto.desktop
/usr/share/kservices5/searchproviders/vimeo.desktop
/usr/share/kservices5/searchproviders/voila.desktop
/usr/share/kservices5/searchproviders/webster.desktop
/usr/share/kservices5/searchproviders/wikia.desktop
/usr/share/kservices5/searchproviders/wikipedia.desktop
/usr/share/kservices5/searchproviders/wiktionary.desktop
/usr/share/kservices5/searchproviders/wolfram_alpha.desktop
/usr/share/kservices5/searchproviders/wordref.desktop
/usr/share/kservices5/searchproviders/yahoo.desktop
/usr/share/kservices5/searchproviders/yahoo_image.desktop
/usr/share/kservices5/searchproviders/yahoo_local.desktop
/usr/share/kservices5/searchproviders/yahoo_shopping.desktop
/usr/share/kservices5/searchproviders/yahoo_video.desktop
/usr/share/kservices5/searchproviders/youtube.desktop
/usr/share/kservices5/smb.desktop
/usr/share/kservices5/useragent.desktop
/usr/share/kservices5/useragentstrings/android10.desktop
/usr/share/kservices5/useragentstrings/chrome10onwinnt51.desktop
/usr/share/kservices5/useragentstrings/chrome22oncurrent.desktop
/usr/share/kservices5/useragentstrings/chrome23oncurrent.desktop
/usr/share/kservices5/useragentstrings/chrome24oncurrent.desktop
/usr/share/kservices5/useragentstrings/chrome50oncurrent.desktop
/usr/share/kservices5/useragentstrings/chrome570oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox15oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox16oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox20oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox30oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox36oncurrent.desktop
/usr/share/kservices5/useragentstrings/firefox520oncurrent.desktop
/usr/share/kservices5/useragentstrings/googlebot.desktop
/usr/share/kservices5/useragentstrings/ie401onwinnt4.desktop
/usr/share/kservices5/useragentstrings/ie50onppc.desktop
/usr/share/kservices5/useragentstrings/ie55onwinnt5.desktop
/usr/share/kservices5/useragentstrings/ie60oncurrent.desktop
/usr/share/kservices5/useragentstrings/ie60onwinnt51.desktop
/usr/share/kservices5/useragentstrings/ie70onwinnt51.desktop
/usr/share/kservices5/useragentstrings/ie80onwinnt60.desktop
/usr/share/kservices5/useragentstrings/ie90onwinnt71.desktop
/usr/share/kservices5/useragentstrings/lynxoncurrent.desktop
/usr/share/kservices5/useragentstrings/nn301oncurrent.desktop
/usr/share/kservices5/useragentstrings/nn475oncurrent.desktop
/usr/share/kservices5/useragentstrings/nn475onwin95.desktop
/usr/share/kservices5/useragentstrings/ns71oncurrent.desktop
/usr/share/kservices5/useragentstrings/ns71onwinnt51.desktop
/usr/share/kservices5/useragentstrings/op1162oncurrent.desktop
/usr/share/kservices5/useragentstrings/op1202oncurrent.desktop
/usr/share/kservices5/useragentstrings/op403onwinnt4.desktop
/usr/share/kservices5/useragentstrings/op85oncurrent.desktop
/usr/share/kservices5/useragentstrings/op90oncurrent.desktop
/usr/share/kservices5/useragentstrings/op962oncurrent.desktop
/usr/share/kservices5/useragentstrings/safari20.desktop
/usr/share/kservices5/useragentstrings/safari30oniphone.desktop
/usr/share/kservices5/useragentstrings/safari32.desktop
/usr/share/kservices5/useragentstrings/safari40.desktop
/usr/share/kservices5/useragentstrings/safari517.desktop
/usr/share/kservices5/useragentstrings/safari60.desktop
/usr/share/kservices5/useragentstrings/w3moncurrent.desktop
/usr/share/kservices5/useragentstrings/wgetoncurrent.desktop
/usr/share/kservices5/webshortcuts.desktop
/usr/share/kservicetypes5/kfileitemactionplugin.desktop
/usr/share/kservicetypes5/kiodndpopupmenuplugin.desktop
/usr/share/kservicetypes5/konqpopupmenuplugin.desktop
/usr/share/kservicetypes5/kpropertiesdialogplugin.desktop
/usr/share/kservicetypes5/kurifilterplugin.desktop
/usr/share/kservicetypes5/searchprovider.desktop
/usr/share/kservicetypes5/uasprovider.desktop
/usr/share/xdg/accept-languages.codes
/usr/share/xdg/kio.categories
/usr/share/xdg/kshorturifilterrc

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KIOCore/KACL
/usr/include/KF5/KIOCore/KCoreDirLister
/usr/include/KF5/KIOCore/KDirNotify
/usr/include/KF5/KIOCore/KDiskFreeSpaceInfo
/usr/include/KF5/KIOCore/KFileItem
/usr/include/KF5/KIOCore/KFileItemListProperties
/usr/include/KF5/KIOCore/KIO/AuthInfo
/usr/include/KF5/KIOCore/KIO/BatchRenameJob
/usr/include/KF5/KIOCore/KIO/ChmodJob
/usr/include/KF5/KIOCore/KIO/ConnectionServer
/usr/include/KF5/KIOCore/KIO/CopyJob
/usr/include/KF5/KIOCore/KIO/DavJob
/usr/include/KF5/KIOCore/KIO/DeleteJob
/usr/include/KF5/KIOCore/KIO/DesktopExecParser
/usr/include/KF5/KIOCore/KIO/DirectorySizeJob
/usr/include/KF5/KIOCore/KIO/EmptyTrashJob
/usr/include/KF5/KIOCore/KIO/FileCopyJob
/usr/include/KF5/KIOCore/KIO/FileJob
/usr/include/KF5/KIOCore/KIO/FileSystemFreeSpaceJob
/usr/include/KF5/KIOCore/KIO/ForwardingSlaveBase
/usr/include/KF5/KIOCore/KIO/Global
/usr/include/KF5/KIOCore/KIO/HostInfo
/usr/include/KF5/KIOCore/KIO/IdleSlave
/usr/include/KF5/KIOCore/KIO/Job
/usr/include/KF5/KIOCore/KIO/JobTracker
/usr/include/KF5/KIOCore/KIO/JobUiDelegateExtension
/usr/include/KF5/KIOCore/KIO/JobUiDelegateFactory
/usr/include/KF5/KIOCore/KIO/ListJob
/usr/include/KF5/KIOCore/KIO/MetaData
/usr/include/KF5/KIOCore/KIO/MimetypeJob
/usr/include/KF5/KIOCore/KIO/MkdirJob
/usr/include/KF5/KIOCore/KIO/MkpathJob
/usr/include/KF5/KIOCore/KIO/MultiGetJob
/usr/include/KF5/KIOCore/KIO/RestoreJob
/usr/include/KF5/KIOCore/KIO/Scheduler
/usr/include/KF5/KIOCore/KIO/SimpleJob
/usr/include/KF5/KIOCore/KIO/Slave
/usr/include/KF5/KIOCore/KIO/SlaveBase
/usr/include/KF5/KIOCore/KIO/SlaveConfig
/usr/include/KF5/KIOCore/KIO/SlaveInterface
/usr/include/KF5/KIOCore/KIO/SpecialJob
/usr/include/KF5/KIOCore/KIO/StatJob
/usr/include/KF5/KIOCore/KIO/StoredTransferJob
/usr/include/KF5/KIOCore/KIO/TCPSlaveBase
/usr/include/KF5/KIOCore/KIO/TransferJob
/usr/include/KF5/KIOCore/KIO/UDSEntry
/usr/include/KF5/KIOCore/KMountPoint
/usr/include/KF5/KIOCore/KNFSShare
/usr/include/KF5/KIOCore/KPasswdServerClient
/usr/include/KF5/KIOCore/KProtocolInfo
/usr/include/KF5/KIOCore/KProtocolManager
/usr/include/KF5/KIOCore/KRecentDocument
/usr/include/KF5/KIOCore/KRemoteEncoding
/usr/include/KF5/KIOCore/KSSLSettings
/usr/include/KF5/KIOCore/KSambaShare
/usr/include/KF5/KIOCore/KSambaShareData
/usr/include/KF5/KIOCore/KSslCertificateManager
/usr/include/KF5/KIOCore/KTcpSocket
/usr/include/KF5/KIOCore/KUrlAuthorized
/usr/include/KF5/KIOCore/kacl.h
/usr/include/KF5/KIOCore/kcoredirlister.h
/usr/include/KF5/KIOCore/kdirnotify.h
/usr/include/KF5/KIOCore/kdiskfreespaceinfo.h
/usr/include/KF5/KIOCore/kfileitem.h
/usr/include/KF5/KIOCore/kfileitemlistproperties.h
/usr/include/KF5/KIOCore/kio/authinfo.h
/usr/include/KF5/KIOCore/kio/batchrenamejob.h
/usr/include/KF5/KIOCore/kio/chmodjob.h
/usr/include/KF5/KIOCore/kio/connectionserver.h
/usr/include/KF5/KIOCore/kio/copyjob.h
/usr/include/KF5/KIOCore/kio/davjob.h
/usr/include/KF5/KIOCore/kio/deletejob.h
/usr/include/KF5/KIOCore/kio/desktopexecparser.h
/usr/include/KF5/KIOCore/kio/directorysizejob.h
/usr/include/KF5/KIOCore/kio/emptytrashjob.h
/usr/include/KF5/KIOCore/kio/filecopyjob.h
/usr/include/KF5/KIOCore/kio/filejob.h
/usr/include/KF5/KIOCore/kio/filesystemfreespacejob.h
/usr/include/KF5/KIOCore/kio/forwardingslavebase.h
/usr/include/KF5/KIOCore/kio/global.h
/usr/include/KF5/KIOCore/kio/hostinfo.h
/usr/include/KF5/KIOCore/kio/http_slave_defaults.h
/usr/include/KF5/KIOCore/kio/idleslave.h
/usr/include/KF5/KIOCore/kio/ioslave_defaults.h
/usr/include/KF5/KIOCore/kio/job.h
/usr/include/KF5/KIOCore/kio/job_base.h
/usr/include/KF5/KIOCore/kio/jobclasses.h
/usr/include/KF5/KIOCore/kio/jobtracker.h
/usr/include/KF5/KIOCore/kio/jobuidelegateextension.h
/usr/include/KF5/KIOCore/kio/jobuidelegatefactory.h
/usr/include/KF5/KIOCore/kio/listjob.h
/usr/include/KF5/KIOCore/kio/metadata.h
/usr/include/KF5/KIOCore/kio/mimetypejob.h
/usr/include/KF5/KIOCore/kio/mkdirjob.h
/usr/include/KF5/KIOCore/kio/mkpathjob.h
/usr/include/KF5/KIOCore/kio/multigetjob.h
/usr/include/KF5/KIOCore/kio/restorejob.h
/usr/include/KF5/KIOCore/kio/scheduler.h
/usr/include/KF5/KIOCore/kio/simplejob.h
/usr/include/KF5/KIOCore/kio/slave.h
/usr/include/KF5/KIOCore/kio/slavebase.h
/usr/include/KF5/KIOCore/kio/slaveconfig.h
/usr/include/KF5/KIOCore/kio/slaveinterface.h
/usr/include/KF5/KIOCore/kio/specialjob.h
/usr/include/KF5/KIOCore/kio/statjob.h
/usr/include/KF5/KIOCore/kio/storedtransferjob.h
/usr/include/KF5/KIOCore/kio/tcpslavebase.h
/usr/include/KF5/KIOCore/kio/transferjob.h
/usr/include/KF5/KIOCore/kio/udsentry.h
/usr/include/KF5/KIOCore/kiocore_export.h
/usr/include/KF5/KIOCore/kmountpoint.h
/usr/include/KF5/KIOCore/knfsshare.h
/usr/include/KF5/KIOCore/kpasswdserverclient.h
/usr/include/KF5/KIOCore/kprotocolinfo.h
/usr/include/KF5/KIOCore/kprotocolmanager.h
/usr/include/KF5/KIOCore/krecentdocument.h
/usr/include/KF5/KIOCore/kremoteencoding.h
/usr/include/KF5/KIOCore/ksambashare.h
/usr/include/KF5/KIOCore/ksambasharedata.h
/usr/include/KF5/KIOCore/ksslcertificatemanager.h
/usr/include/KF5/KIOCore/ksslcertificatemanager_p.h
/usr/include/KF5/KIOCore/ksslsettings.h
/usr/include/KF5/KIOCore/ktcpsocket.h
/usr/include/KF5/KIOCore/kurlauthorized.h
/usr/include/KF5/KIOFileWidgets/KAbstractViewAdapter
/usr/include/KF5/KIOFileWidgets/KDirOperator
/usr/include/KF5/KIOFileWidgets/KDirSortFilterProxyModel
/usr/include/KF5/KIOFileWidgets/KEncodingFileDialog
/usr/include/KF5/KIOFileWidgets/KFileCopyToMenu
/usr/include/KF5/KIOFileWidgets/KFileFilterCombo
/usr/include/KF5/KIOFileWidgets/KFilePlaceEditDialog
/usr/include/KF5/KIOFileWidgets/KFilePlacesModel
/usr/include/KF5/KIOFileWidgets/KFilePlacesView
/usr/include/KF5/KIOFileWidgets/KFilePreviewGenerator
/usr/include/KF5/KIOFileWidgets/KFileWidget
/usr/include/KF5/KIOFileWidgets/KImageFilePreview
/usr/include/KF5/KIOFileWidgets/KNameAndUrlInputDialog
/usr/include/KF5/KIOFileWidgets/KNewFileMenu
/usr/include/KF5/KIOFileWidgets/KPreviewWidgetBase
/usr/include/KF5/KIOFileWidgets/KRecentDirs
/usr/include/KF5/KIOFileWidgets/KStatusBarOfflineIndicator
/usr/include/KF5/KIOFileWidgets/KUrlNavigator
/usr/include/KF5/KIOFileWidgets/kabstractviewadapter.h
/usr/include/KF5/KIOFileWidgets/kdiroperator.h
/usr/include/KF5/KIOFileWidgets/kdirsortfilterproxymodel.h
/usr/include/KF5/KIOFileWidgets/kencodingfiledialog.h
/usr/include/KF5/KIOFileWidgets/kfilecopytomenu.h
/usr/include/KF5/KIOFileWidgets/kfilefiltercombo.h
/usr/include/KF5/KIOFileWidgets/kfileplaceeditdialog.h
/usr/include/KF5/KIOFileWidgets/kfileplacesmodel.h
/usr/include/KF5/KIOFileWidgets/kfileplacesview.h
/usr/include/KF5/KIOFileWidgets/kfilepreviewgenerator.h
/usr/include/KF5/KIOFileWidgets/kfilewidget.h
/usr/include/KF5/KIOFileWidgets/kimagefilepreview.h
/usr/include/KF5/KIOFileWidgets/kiofilewidgets_export.h
/usr/include/KF5/KIOFileWidgets/knameandurlinputdialog.h
/usr/include/KF5/KIOFileWidgets/knewfilemenu.h
/usr/include/KF5/KIOFileWidgets/kpreviewwidgetbase.h
/usr/include/KF5/KIOFileWidgets/krecentdirs.h
/usr/include/KF5/KIOFileWidgets/kstatusbarofflineindicator.h
/usr/include/KF5/KIOFileWidgets/kurlnavigator.h
/usr/include/KF5/KIOGui/KIO/FavIconRequestJob
/usr/include/KF5/KIOGui/kio/faviconrequestjob.h
/usr/include/KF5/KIOGui/kiogui_export.h
/usr/include/KF5/KIOWidgets/KAbstractFileItemActionPlugin
/usr/include/KF5/KIOWidgets/KAutoMount
/usr/include/KF5/KIOWidgets/KBuildSycocaProgressDialog
/usr/include/KF5/KIOWidgets/KDesktopFileActions
/usr/include/KF5/KIOWidgets/KDirLister
/usr/include/KF5/KIOWidgets/KDirModel
/usr/include/KF5/KIOWidgets/KFile
/usr/include/KF5/KIOWidgets/KFileItemActions
/usr/include/KF5/KIOWidgets/KFileItemDelegate
/usr/include/KF5/KIOWidgets/KIO/AccessManager
/usr/include/KF5/KIOWidgets/KIO/DndPopupMenuPlugin
/usr/include/KF5/KIOWidgets/KIO/DropJob
/usr/include/KF5/KIOWidgets/KIO/FileUndoManager
/usr/include/KF5/KIOWidgets/KIO/JobUiDelegate
/usr/include/KF5/KIOWidgets/KIO/KUriFilterSearchProviderActions
/usr/include/KF5/KIOWidgets/KIO/OpenFileManagerWindowJob
/usr/include/KF5/KIOWidgets/KIO/Paste
/usr/include/KF5/KIOWidgets/KIO/PasteJob
/usr/include/KF5/KIOWidgets/KIO/PixmapLoader
/usr/include/KF5/KIOWidgets/KIO/PreviewJob
/usr/include/KF5/KIOWidgets/KIO/RenameDialog
/usr/include/KF5/KIOWidgets/KIO/SkipDialog
/usr/include/KF5/KIOWidgets/KIO/SslUi
/usr/include/KF5/KIOWidgets/KIO/ThumbCreator
/usr/include/KF5/KIOWidgets/KIO/ThumbSequenceCreator
/usr/include/KF5/KIOWidgets/KOpenWithDialog
/usr/include/KF5/KIOWidgets/KOverlayIconPlugin
/usr/include/KF5/KIOWidgets/KPropertiesDialog
/usr/include/KF5/KIOWidgets/KRun
/usr/include/KF5/KIOWidgets/KShellCompletion
/usr/include/KF5/KIOWidgets/KSslCertificateBox
/usr/include/KF5/KIOWidgets/KSslInfoDialog
/usr/include/KF5/KIOWidgets/KUriFilter
/usr/include/KF5/KIOWidgets/KUrlComboBox
/usr/include/KF5/KIOWidgets/KUrlCompletion
/usr/include/KF5/KIOWidgets/KUrlPixmapProvider
/usr/include/KF5/KIOWidgets/KUrlRequester
/usr/include/KF5/KIOWidgets/KUrlRequesterDialog
/usr/include/KF5/KIOWidgets/kabstractfileitemactionplugin.h
/usr/include/KF5/KIOWidgets/kautomount.h
/usr/include/KF5/KIOWidgets/kbuildsycocaprogressdialog.h
/usr/include/KF5/KIOWidgets/kdesktopfileactions.h
/usr/include/KF5/KIOWidgets/kdirlister.h
/usr/include/KF5/KIOWidgets/kdirmodel.h
/usr/include/KF5/KIOWidgets/kfile.h
/usr/include/KF5/KIOWidgets/kfileitemactions.h
/usr/include/KF5/KIOWidgets/kfileitemdelegate.h
/usr/include/KF5/KIOWidgets/kio/accessmanager.h
/usr/include/KF5/KIOWidgets/kio/dndpopupmenuplugin.h
/usr/include/KF5/KIOWidgets/kio/dropjob.h
/usr/include/KF5/KIOWidgets/kio/fileundomanager.h
/usr/include/KF5/KIOWidgets/kio/jobuidelegate.h
/usr/include/KF5/KIOWidgets/kio/kurifiltersearchprovideractions.h
/usr/include/KF5/KIOWidgets/kio/openfilemanagerwindowjob.h
/usr/include/KF5/KIOWidgets/kio/paste.h
/usr/include/KF5/KIOWidgets/kio/pastejob.h
/usr/include/KF5/KIOWidgets/kio/pixmaploader.h
/usr/include/KF5/KIOWidgets/kio/previewjob.h
/usr/include/KF5/KIOWidgets/kio/renamedialog.h
/usr/include/KF5/KIOWidgets/kio/skipdialog.h
/usr/include/KF5/KIOWidgets/kio/sslui.h
/usr/include/KF5/KIOWidgets/kio/thumbcreator.h
/usr/include/KF5/KIOWidgets/kio/thumbsequencecreator.h
/usr/include/KF5/KIOWidgets/kiowidgets_export.h
/usr/include/KF5/KIOWidgets/kopenwithdialog.h
/usr/include/KF5/KIOWidgets/koverlayiconplugin.h
/usr/include/KF5/KIOWidgets/kpropertiesdialog.h
/usr/include/KF5/KIOWidgets/krun.h
/usr/include/KF5/KIOWidgets/kshellcompletion.h
/usr/include/KF5/KIOWidgets/ksslcertificatebox.h
/usr/include/KF5/KIOWidgets/ksslinfodialog.h
/usr/include/KF5/KIOWidgets/kurifilter.h
/usr/include/KF5/KIOWidgets/kurlcombobox.h
/usr/include/KF5/KIOWidgets/kurlcompletion.h
/usr/include/KF5/KIOWidgets/kurlpixmapprovider.h
/usr/include/KF5/KIOWidgets/kurlrequester.h
/usr/include/KF5/KIOWidgets/kurlrequesterdialog.h
/usr/include/KF5/kio/kntlm.h
/usr/include/KF5/kio/kntlm_export.h
/usr/include/KF5/kio_version.h
/usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake
/usr/lib64/cmake/KF5KIO/KF5KIOConfigVersion.cmake
/usr/lib64/cmake/KF5KIO/KF5KIOTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5KIO/KF5KIOTargets.cmake
/usr/lib64/libKF5KIOCore.so
/usr/lib64/libKF5KIOFileWidgets.so
/usr/lib64/libKF5KIOGui.so
/usr/lib64/libKF5KIONTLM.so
/usr/lib64/libKF5KIOWidgets.so
/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri
/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri
/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/ca/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/data/index.docbook
/usr/share/doc/HTML/ca/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/file/index.docbook
/usr/share/doc/HTML/ca/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/ca/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/ca/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/help/index.docbook
/usr/share/doc/HTML/ca/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/http/index.docbook
/usr/share/doc/HTML/ca/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/ca/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/ca/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/ca/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/de/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/de/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/de/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/de/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/de/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/de/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/de/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/de/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/de/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/data/index.docbook
/usr/share/doc/HTML/de/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/file/index.docbook
/usr/share/doc/HTML/de/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/de/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/de/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/help/index.docbook
/usr/share/doc/HTML/de/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/http/index.docbook
/usr/share/doc/HTML/de/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/de/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/de/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/de/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/en/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/en/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/en/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/en/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/en/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/en/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/en/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/en/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/en/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/data/index.docbook
/usr/share/doc/HTML/en/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/file/index.docbook
/usr/share/doc/HTML/en/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/en/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/en/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/help/index.docbook
/usr/share/doc/HTML/en/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/http/index.docbook
/usr/share/doc/HTML/en/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/en/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/en/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/en/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/es/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/es/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/es/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/es/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/es/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/es/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/es/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/es/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/es/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/data/index.docbook
/usr/share/doc/HTML/es/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/file/index.docbook
/usr/share/doc/HTML/es/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/es/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/es/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/help/index.docbook
/usr/share/doc/HTML/es/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/http/index.docbook
/usr/share/doc/HTML/es/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/es/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/es/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/es/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/et/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/data/index.docbook
/usr/share/doc/HTML/et/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/file/index.docbook
/usr/share/doc/HTML/et/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/et/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/help/index.docbook
/usr/share/doc/HTML/et/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/http/index.docbook
/usr/share/doc/HTML/et/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/et/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/et/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/et/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/it/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/it/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/it/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/it/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/it/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/it/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/it/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/it/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/it/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/data/index.docbook
/usr/share/doc/HTML/it/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/file/index.docbook
/usr/share/doc/HTML/it/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/it/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/it/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/help/index.docbook
/usr/share/doc/HTML/it/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/http/index.docbook
/usr/share/doc/HTML/it/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/it/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/it/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/it/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/nl/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/data/index.docbook
/usr/share/doc/HTML/nl/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/file/index.docbook
/usr/share/doc/HTML/nl/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/nl/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/nl/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/help/index.docbook
/usr/share/doc/HTML/nl/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/http/index.docbook
/usr/share/doc/HTML/nl/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/nl/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/nl/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/nl/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/pt/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/data/index.docbook
/usr/share/doc/HTML/pt/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/file/index.docbook
/usr/share/doc/HTML/pt/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/pt/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/pt/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/help/index.docbook
/usr/share/doc/HTML/pt/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/http/index.docbook
/usr/share/doc/HTML/pt/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/pt/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/pt/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/pt/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/data/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/file/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/help/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/http/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/pt_BR/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/ru/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/ru/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/data/index.docbook
/usr/share/doc/HTML/ru/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/file/index.docbook
/usr/share/doc/HTML/ru/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/ru/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/ru/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/help/index.docbook
/usr/share/doc/HTML/ru/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/ru/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/ru/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/sr/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/data/index.docbook
/usr/share/doc/HTML/sr/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/file/index.docbook
/usr/share/doc/HTML/sr/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/sr/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sr/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/help/index.docbook
/usr/share/doc/HTML/sr/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/http/index.docbook
/usr/share/doc/HTML/sr/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/sr/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/sr/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/sr/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/data/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/file/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/help/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/http/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/sr@latin/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/sv/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/data/index.docbook
/usr/share/doc/HTML/sv/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/file/index.docbook
/usr/share/doc/HTML/sv/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/sv/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sv/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/help/index.docbook
/usr/share/doc/HTML/sv/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/http/index.docbook
/usr/share/doc/HTML/sv/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/sv/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/sv/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/sv/kioslave5/webdav/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/cache/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/cache/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/cookies/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/cookies/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/netpref/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/netpref/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/proxy/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/proxy/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/smb/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/smb/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/trash/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/trash/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/useragent/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/useragent/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/webshortcuts/index.docbook
/usr/share/doc/HTML/uk/kioslave5/data/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/data/index.docbook
/usr/share/doc/HTML/uk/kioslave5/file/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/file/index.docbook
/usr/share/doc/HTML/uk/kioslave5/ftp/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/ftp/index.docbook
/usr/share/doc/HTML/uk/kioslave5/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/uk/kioslave5/help/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/help/index.docbook
/usr/share/doc/HTML/uk/kioslave5/http/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/http/index.docbook
/usr/share/doc/HTML/uk/kioslave5/mailto/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/mailto/index.docbook
/usr/share/doc/HTML/uk/kioslave5/telnet/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/telnet/index.docbook
/usr/share/doc/HTML/uk/kioslave5/webdav/index.cache.bz2
/usr/share/doc/HTML/uk/kioslave5/webdav/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5KIOCore.so.5
/usr/lib64/libKF5KIOCore.so.5.55.0
/usr/lib64/libKF5KIOFileWidgets.so.5
/usr/lib64/libKF5KIOFileWidgets.so.5.55.0
/usr/lib64/libKF5KIOGui.so.5
/usr/lib64/libKF5KIOGui.so.5.55.0
/usr/lib64/libKF5KIONTLM.so.5
/usr/lib64/libKF5KIONTLM.so.5.55.0
/usr/lib64/libKF5KIOWidgets.so.5
/usr/lib64/libKF5KIOWidgets.so.5.55.0
/usr/lib64/qt5/plugins/kcm_kio.so
/usr/lib64/qt5/plugins/kcm_trash.so
/usr/lib64/qt5/plugins/kcm_webshortcuts.so
/usr/lib64/qt5/plugins/kf5/kded/kcookiejar.so
/usr/lib64/qt5/plugins/kf5/kded/proxyscout.so
/usr/lib64/qt5/plugins/kf5/kded/remotenotifier.so
/usr/lib64/qt5/plugins/kf5/kio/file.so
/usr/lib64/qt5/plugins/kf5/kio/ftp.so
/usr/lib64/qt5/plugins/kf5/kio/ghelp.so
/usr/lib64/qt5/plugins/kf5/kio/help.so
/usr/lib64/qt5/plugins/kf5/kio/http.so
/usr/lib64/qt5/plugins/kf5/kio/remote.so
/usr/lib64/qt5/plugins/kf5/kio/trash.so
/usr/lib64/qt5/plugins/kf5/kiod/kioexecd.so
/usr/lib64/qt5/plugins/kf5/kiod/kpasswdserver.so
/usr/lib64/qt5/plugins/kf5/kiod/kssld.so
/usr/lib64/qt5/plugins/kf5/urifilters/fixhosturifilter.so
/usr/lib64/qt5/plugins/kf5/urifilters/kshorturifilter.so
/usr/lib64/qt5/plugins/kf5/urifilters/kuriikwsfilter.so
/usr/lib64/qt5/plugins/kf5/urifilters/kurisearchfilter.so
/usr/lib64/qt5/plugins/kf5/urifilters/localdomainurifilter.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kio/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man8/kcookiejar5.8
/usr/share/man/de/man8/kcookiejar5.8
/usr/share/man/es/man8/kcookiejar5.8
/usr/share/man/it/man8/kcookiejar5.8
/usr/share/man/man8/kcookiejar5.8
/usr/share/man/nl/man8/kcookiejar5.8
/usr/share/man/pt/man8/kcookiejar5.8
/usr/share/man/pt_BR/man8/kcookiejar5.8
/usr/share/man/sv/man8/kcookiejar5.8
/usr/share/man/uk/man8/kcookiejar5.8

%files locales -f kio5.lang
%defattr(-,root,root,-)

