#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: 1bec16f
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : kio
Version  : 6.4.1
Release  : 93
URL      : https://download.kde.org/stable/frameworks/6.4/kio-6.4.1.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.4/kio-6.4.1.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.4/kio-6.4.1.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : Resource and network access abstraction
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: kio-bin = %{version}-%{release}
Requires: kio-data = %{version}-%{release}
Requires: kio-lib = %{version}-%{release}
Requires: kio-license = %{version}-%{release}
Requires: kio-locales = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : karchive-dev
BuildRequires : kbookmarks-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfig
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kded-dev
BuildRequires : kdoctools-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kio-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : knotifications-dev
BuildRequires : krb5-dev
BuildRequires : kservice-dev
BuildRequires : kwallet-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kxmlgui-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : qt5compat-dev
BuildRequires : qt6base-dev
BuildRequires : ruby
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : util-linux-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
kioexec is launched when the user wants to open a remote file with
an application that only supports local files.

%package bin
Summary: bin components for the kio package.
Group: Binaries
Requires: kio-data = %{version}-%{release}
Requires: kio-license = %{version}-%{release}

%description bin
bin components for the kio package.


%package data
Summary: data components for the kio package.
Group: Data

%description data
data components for the kio package.


%package dev
Summary: dev components for the kio package.
Group: Development
Requires: kio-lib = %{version}-%{release}
Requires: kio-bin = %{version}-%{release}
Requires: kio-data = %{version}-%{release}
Provides: kio-devel = %{version}-%{release}
Requires: kio = %{version}-%{release}

%description dev
dev components for the kio package.


%package doc
Summary: doc components for the kio package.
Group: Documentation

%description doc
doc components for the kio package.


%package lib
Summary: lib components for the kio package.
Group: Libraries
Requires: kio-data = %{version}-%{release}
Requires: kio-license = %{version}-%{release}

%description lib
lib components for the kio package.


%package license
Summary: license components for the kio package.
Group: Default

%description license
license components for the kio package.


%package locales
Summary: locales components for the kio package.
Group: Default

%description locales
locales components for the kio package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n kio-6.4.1
cd %{_builddir}/kio-6.4.1
pushd ..
cp -a kio-6.4.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721410212
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721410212
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kio
cp %{_builddir}/kio-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kio/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e || :
cp %{_builddir}/kio-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kio/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kio-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kio/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kio-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kio/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/kio-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kio/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/kio-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kio/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kio-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kio/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kio-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kio/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kio-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kio/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/kio-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kio/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/kio-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kio/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/kio-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kio/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kio-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kio/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kio-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kio/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kio-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kio/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kio-%{version}/templates/kioworker6/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kio/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/kio-%{version}/tests/messageboxworker/messageboxworker.json.license %{buildroot}/usr/share/package-licenses/kio/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kio6
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/kf6/kiod6
/V3/usr/lib64/libexec/kf6/kioexec
/V3/usr/lib64/libexec/kf6/kioworker
/usr/lib64/libexec/kf6/kiod6
/usr/lib64/libexec/kf6/kioexec
/usr/lib64/libexec/kf6/kioworker

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ktelnetservice6
/V3/usr/bin/ktrash6
/usr/bin/ktelnetservice6
/usr/bin/ktrash6

%files data
%defattr(-,root,root,-)
/usr/share/applications/ktelnetservice6.desktop
/usr/share/applications/org.kde.kiod6.desktop
/usr/share/dbus-1/services/org.kde.kiod6.service
/usr/share/dbus-1/services/org.kde.kioexecd6.service
/usr/share/dbus-1/services/org.kde.kpasswdserver6.service
/usr/share/dbus-1/services/org.kde.kssld6.service
/usr/share/kdevappwizard/templates/kioworker6.tar.bz2
/usr/share/kf6/searchproviders/7digital.desktop
/usr/share/kf6/searchproviders/acronym.desktop
/usr/share/kf6/searchproviders/amazon.desktop
/usr/share/kf6/searchproviders/amazon_mp3.desktop
/usr/share/kf6/searchproviders/amg.desktop
/usr/share/kf6/searchproviders/archpkg.desktop
/usr/share/kf6/searchproviders/archwiki.desktop
/usr/share/kf6/searchproviders/backports.desktop
/usr/share/kf6/searchproviders/baidu.desktop
/usr/share/kf6/searchproviders/beolingus.desktop
/usr/share/kf6/searchproviders/bing.desktop
/usr/share/kf6/searchproviders/boo.desktop
/usr/share/kf6/searchproviders/bug.desktop
/usr/share/kf6/searchproviders/call.desktop
/usr/share/kf6/searchproviders/cia.desktop
/usr/share/kf6/searchproviders/citeseer.desktop
/usr/share/kf6/searchproviders/codeberg.desktop
/usr/share/kf6/searchproviders/cpan.desktop
/usr/share/kf6/searchproviders/cplusplus.desktop
/usr/share/kf6/searchproviders/cppreference.desktop
/usr/share/kf6/searchproviders/ctan.desktop
/usr/share/kf6/searchproviders/ctan_cat.desktop
/usr/share/kf6/searchproviders/dbug.desktop
/usr/share/kf6/searchproviders/de2en.desktop
/usr/share/kf6/searchproviders/de2fr.desktop
/usr/share/kf6/searchproviders/deb.desktop
/usr/share/kf6/searchproviders/deepl.desktop
/usr/share/kf6/searchproviders/dictfr.desktop
/usr/share/kf6/searchproviders/docbook.desktop
/usr/share/kf6/searchproviders/doi.desktop
/usr/share/kf6/searchproviders/duckduckgo.desktop
/usr/share/kf6/searchproviders/duckduckgo_info.desktop
/usr/share/kf6/searchproviders/duckduckgo_shopping.desktop
/usr/share/kf6/searchproviders/ecosia.desktop
/usr/share/kf6/searchproviders/en2de.desktop
/usr/share/kf6/searchproviders/en2es.desktop
/usr/share/kf6/searchproviders/en2fr.desktop
/usr/share/kf6/searchproviders/en2it.desktop
/usr/share/kf6/searchproviders/es2en.desktop
/usr/share/kf6/searchproviders/facebook.desktop
/usr/share/kf6/searchproviders/feedster.desktop
/usr/share/kf6/searchproviders/flatpak.desktop
/usr/share/kf6/searchproviders/flickr.desktop
/usr/share/kf6/searchproviders/flickrcc.desktop
/usr/share/kf6/searchproviders/foldoc.desktop
/usr/share/kf6/searchproviders/fr2de.desktop
/usr/share/kf6/searchproviders/fr2en.desktop
/usr/share/kf6/searchproviders/freecode.desktop
/usr/share/kf6/searchproviders/freedb.desktop
/usr/share/kf6/searchproviders/fsd.desktop
/usr/share/kf6/searchproviders/github.desktop
/usr/share/kf6/searchproviders/gitlab.desktop
/usr/share/kf6/searchproviders/google.desktop
/usr/share/kf6/searchproviders/google_advanced.desktop
/usr/share/kf6/searchproviders/google_code.desktop
/usr/share/kf6/searchproviders/google_groups.desktop
/usr/share/kf6/searchproviders/google_images.desktop
/usr/share/kf6/searchproviders/google_lucky.desktop
/usr/share/kf6/searchproviders/google_maps.desktop
/usr/share/kf6/searchproviders/google_movie.desktop
/usr/share/kf6/searchproviders/google_news.desktop
/usr/share/kf6/searchproviders/google_shopping.desktop
/usr/share/kf6/searchproviders/grec.desktop
/usr/share/kf6/searchproviders/hyperdictionary.desktop
/usr/share/kf6/searchproviders/hyperdictionary_thesaurus.desktop
/usr/share/kf6/searchproviders/identica_groups.desktop
/usr/share/kf6/searchproviders/identica_notices.desktop
/usr/share/kf6/searchproviders/identica_people.desktop
/usr/share/kf6/searchproviders/imdb.desktop
/usr/share/kf6/searchproviders/invent.desktop
/usr/share/kf6/searchproviders/invent_issues.desktop
/usr/share/kf6/searchproviders/invent_mr.desktop
/usr/share/kf6/searchproviders/invent_repo.desktop
/usr/share/kf6/searchproviders/it2en.desktop
/usr/share/kf6/searchproviders/jamendo.desktop
/usr/share/kf6/searchproviders/jeeves.desktop
/usr/share/kf6/searchproviders/kde.desktop
/usr/share/kf6/searchproviders/kde_apps.desktop
/usr/share/kf6/searchproviders/kde_forums.desktop
/usr/share/kf6/searchproviders/kde_store.desktop
/usr/share/kf6/searchproviders/kde_techbase.desktop
/usr/share/kf6/searchproviders/kde_userbase.desktop
/usr/share/kf6/searchproviders/kreddit.desktop
/usr/share/kf6/searchproviders/krita.desktop
/usr/share/kf6/searchproviders/learncpp.desktop
/usr/share/kf6/searchproviders/leo.desktop
/usr/share/kf6/searchproviders/linguee.desktop
/usr/share/kf6/searchproviders/magnatune.desktop
/usr/share/kf6/searchproviders/metacrawler.desktop
/usr/share/kf6/searchproviders/microsoft_cpp.desktop
/usr/share/kf6/searchproviders/msdn.desktop
/usr/share/kf6/searchproviders/multitran-deru.desktop
/usr/share/kf6/searchproviders/multitran-enru.desktop
/usr/share/kf6/searchproviders/multitran-esru.desktop
/usr/share/kf6/searchproviders/multitran-frru.desktop
/usr/share/kf6/searchproviders/multitran-itru.desktop
/usr/share/kf6/searchproviders/multitran-nlru.desktop
/usr/share/kf6/searchproviders/netcraft.desktop
/usr/share/kf6/searchproviders/nl-telephone.desktop
/usr/share/kf6/searchproviders/nl-teletekst.desktop
/usr/share/kf6/searchproviders/opendesktop.desktop
/usr/share/kf6/searchproviders/opensuse.desktop
/usr/share/kf6/searchproviders/pgpkeys.desktop
/usr/share/kf6/searchproviders/php.desktop
/usr/share/kf6/searchproviders/protondb.desktop
/usr/share/kf6/searchproviders/pypi.desktop
/usr/share/kf6/searchproviders/python.desktop
/usr/share/kf6/searchproviders/qt5.desktop
/usr/share/kf6/searchproviders/qt6.desktop
/usr/share/kf6/searchproviders/qwant.desktop
/usr/share/kf6/searchproviders/qwant_images.desktop
/usr/share/kf6/searchproviders/qwant_news.desktop
/usr/share/kf6/searchproviders/qwant_shopping.desktop
/usr/share/kf6/searchproviders/qwant_social.desktop
/usr/share/kf6/searchproviders/qwant_videos.desktop
/usr/share/kf6/searchproviders/rae.desktop
/usr/share/kf6/searchproviders/rag.desktop
/usr/share/kf6/searchproviders/reddit.desktop
/usr/share/kf6/searchproviders/rfc.desktop
/usr/share/kf6/searchproviders/rpmfind.desktop
/usr/share/kf6/searchproviders/ruby_application_archive.desktop
/usr/share/kf6/searchproviders/rust.desktop
/usr/share/kf6/searchproviders/soundcloud.desktop
/usr/share/kf6/searchproviders/sourceforge.desktop
/usr/share/kf6/searchproviders/technorati.desktop
/usr/share/kf6/searchproviders/technoratitags.desktop
/usr/share/kf6/searchproviders/thesaurus.desktop
/usr/share/kf6/searchproviders/tvtome.desktop
/usr/share/kf6/searchproviders/ubuntu.desktop
/usr/share/kf6/searchproviders/urbandictionary.desktop
/usr/share/kf6/searchproviders/uspto.desktop
/usr/share/kf6/searchproviders/vimeo.desktop
/usr/share/kf6/searchproviders/voila.desktop
/usr/share/kf6/searchproviders/webster.desktop
/usr/share/kf6/searchproviders/wikia.desktop
/usr/share/kf6/searchproviders/wikipedia.desktop
/usr/share/kf6/searchproviders/wiktionary.desktop
/usr/share/kf6/searchproviders/wine.desktop
/usr/share/kf6/searchproviders/wolfram_alpha.desktop
/usr/share/kf6/searchproviders/wordref.desktop
/usr/share/kf6/searchproviders/yahoo.desktop
/usr/share/kf6/searchproviders/yahoo_image.desktop
/usr/share/kf6/searchproviders/yahoo_local.desktop
/usr/share/kf6/searchproviders/yahoo_shopping.desktop
/usr/share/kf6/searchproviders/yahoo_video.desktop
/usr/share/kf6/searchproviders/yandex.desktop
/usr/share/kf6/searchproviders/youtube.desktop
/usr/share/qlogging-categories6/kio.categories
/usr/share/qlogging-categories6/kio.renamecategories

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libkuriikwsfiltereng_private.so
/usr/include/KF6/KIO/kio_version.h
/usr/include/KF6/KIOCore/KACL
/usr/include/KF6/KIOCore/KCoreDirLister
/usr/include/KF6/KIOCore/KDirNotify
/usr/include/KF6/KIOCore/KFileFilter
/usr/include/KF6/KIOCore/KFileItem
/usr/include/KF6/KIOCore/KFileItemListProperties
/usr/include/KF6/KIOCore/KIO/AskUserActionInterface
/usr/include/KF6/KIOCore/KIO/AuthInfo
/usr/include/KF6/KIOCore/KIO/BatchRenameJob
/usr/include/KF6/KIOCore/KIO/ChmodJob
/usr/include/KF6/KIOCore/KIO/CopyJob
/usr/include/KF6/KIOCore/KIO/DavJob
/usr/include/KF6/KIOCore/KIO/DeleteJob
/usr/include/KF6/KIOCore/KIO/DesktopExecParser
/usr/include/KF6/KIOCore/KIO/DirectorySizeJob
/usr/include/KF6/KIOCore/KIO/EmptyTrashJob
/usr/include/KF6/KIOCore/KIO/FileCopyJob
/usr/include/KF6/KIOCore/KIO/FileJob
/usr/include/KF6/KIOCore/KIO/FileSystemFreeSpaceJob
/usr/include/KF6/KIOCore/KIO/ForwardingWorkerBase
/usr/include/KF6/KIOCore/KIO/Global
/usr/include/KF6/KIOCore/KIO/Job
/usr/include/KF6/KIOCore/KIO/JobTracker
/usr/include/KF6/KIOCore/KIO/JobUiDelegateExtension
/usr/include/KF6/KIOCore/KIO/JobUiDelegateFactory
/usr/include/KF6/KIOCore/KIO/ListJob
/usr/include/KF6/KIOCore/KIO/MetaData
/usr/include/KF6/KIOCore/KIO/MimeTypeFinderJob
/usr/include/KF6/KIOCore/KIO/MimetypeJob
/usr/include/KF6/KIOCore/KIO/MkdirJob
/usr/include/KF6/KIOCore/KIO/MkpathJob
/usr/include/KF6/KIOCore/KIO/NameFinderJob
/usr/include/KF6/KIOCore/KIO/OpenWith
/usr/include/KF6/KIOCore/KIO/RestoreJob
/usr/include/KF6/KIOCore/KIO/SimpleJob
/usr/include/KF6/KIOCore/KIO/SpecialJob
/usr/include/KF6/KIOCore/KIO/StatJob
/usr/include/KF6/KIOCore/KIO/StoredTransferJob
/usr/include/KF6/KIOCore/KIO/TransferJob
/usr/include/KF6/KIOCore/KIO/UDSEntry
/usr/include/KF6/KIOCore/KIO/UntrustedProgramHandlerInterface
/usr/include/KF6/KIOCore/KIO/WorkerBase
/usr/include/KF6/KIOCore/KIO/WorkerFactory
/usr/include/KF6/KIOCore/KMountPoint
/usr/include/KF6/KIOCore/KOverlayIconPlugin
/usr/include/KF6/KIOCore/KPasswdServerClient
/usr/include/KF6/KIOCore/KProtocolInfo
/usr/include/KF6/KIOCore/KProtocolManager
/usr/include/KF6/KIOCore/KRecentDirs
/usr/include/KF6/KIOCore/KRecentDocument
/usr/include/KF6/KIOCore/KRemoteEncoding
/usr/include/KF6/KIOCore/KSambaShare
/usr/include/KF6/KIOCore/KSambaShareData
/usr/include/KF6/KIOCore/KSslErrorUiData
/usr/include/KF6/KIOCore/KUrlAuthorized
/usr/include/KF6/KIOCore/kacl.h
/usr/include/KF6/KIOCore/kcoredirlister.h
/usr/include/KF6/KIOCore/kdirnotify.h
/usr/include/KF6/KIOCore/kfilefilter.h
/usr/include/KF6/KIOCore/kfileitem.h
/usr/include/KF6/KIOCore/kfileitemlistproperties.h
/usr/include/KF6/KIOCore/kio/askuseractioninterface.h
/usr/include/KF6/KIOCore/kio/authinfo.h
/usr/include/KF6/KIOCore/kio/batchrenamejob.h
/usr/include/KF6/KIOCore/kio/chmodjob.h
/usr/include/KF6/KIOCore/kio/copyjob.h
/usr/include/KF6/KIOCore/kio/davjob.h
/usr/include/KF6/KIOCore/kio/deletejob.h
/usr/include/KF6/KIOCore/kio/desktopexecparser.h
/usr/include/KF6/KIOCore/kio/directorysizejob.h
/usr/include/KF6/KIOCore/kio/emptytrashjob.h
/usr/include/KF6/KIOCore/kio/filecopyjob.h
/usr/include/KF6/KIOCore/kio/filejob.h
/usr/include/KF6/KIOCore/kio/filesystemfreespacejob.h
/usr/include/KF6/KIOCore/kio/forwardingworkerbase.h
/usr/include/KF6/KIOCore/kio/global.h
/usr/include/KF6/KIOCore/kio/ioworker_defaults.h
/usr/include/KF6/KIOCore/kio/job.h
/usr/include/KF6/KIOCore/kio/job_base.h
/usr/include/KF6/KIOCore/kio/jobtracker.h
/usr/include/KF6/KIOCore/kio/jobuidelegateextension.h
/usr/include/KF6/KIOCore/kio/jobuidelegatefactory.h
/usr/include/KF6/KIOCore/kio/listjob.h
/usr/include/KF6/KIOCore/kio/metadata.h
/usr/include/KF6/KIOCore/kio/mimetypefinderjob.h
/usr/include/KF6/KIOCore/kio/mimetypejob.h
/usr/include/KF6/KIOCore/kio/mkdirjob.h
/usr/include/KF6/KIOCore/kio/mkpathjob.h
/usr/include/KF6/KIOCore/kio/namefinderjob.h
/usr/include/KF6/KIOCore/kio/openwith.h
/usr/include/KF6/KIOCore/kio/restorejob.h
/usr/include/KF6/KIOCore/kio/simplejob.h
/usr/include/KF6/KIOCore/kio/specialjob.h
/usr/include/KF6/KIOCore/kio/statjob.h
/usr/include/KF6/KIOCore/kio/storedtransferjob.h
/usr/include/KF6/KIOCore/kio/transferjob.h
/usr/include/KF6/KIOCore/kio/udsentry.h
/usr/include/KF6/KIOCore/kio/untrustedprogramhandlerinterface.h
/usr/include/KF6/KIOCore/kio/workerbase.h
/usr/include/KF6/KIOCore/kio/workerfactory.h
/usr/include/KF6/KIOCore/kiocore_export.h
/usr/include/KF6/KIOCore/kmountpoint.h
/usr/include/KF6/KIOCore/koverlayiconplugin.h
/usr/include/KF6/KIOCore/kpasswdserverclient.h
/usr/include/KF6/KIOCore/kprotocolinfo.h
/usr/include/KF6/KIOCore/kprotocolmanager.h
/usr/include/KF6/KIOCore/krecentdirs.h
/usr/include/KF6/KIOCore/krecentdocument.h
/usr/include/KF6/KIOCore/kremoteencoding.h
/usr/include/KF6/KIOCore/ksambashare.h
/usr/include/KF6/KIOCore/ksambasharedata.h
/usr/include/KF6/KIOCore/ksslerroruidata.h
/usr/include/KF6/KIOCore/kurlauthorized.h
/usr/include/KF6/KIOFileWidgets/KAbstractViewAdapter
/usr/include/KF6/KIOFileWidgets/KDirOperator
/usr/include/KF6/KIOFileWidgets/KDirSortFilterProxyModel
/usr/include/KF6/KIOFileWidgets/KEncodingFileDialog
/usr/include/KF6/KIOFileWidgets/KFileCopyToMenu
/usr/include/KF6/KIOFileWidgets/KFileCustomDialog
/usr/include/KF6/KIOFileWidgets/KFileFilterCombo
/usr/include/KF6/KIOFileWidgets/KFilePlaceEditDialog
/usr/include/KF6/KIOFileWidgets/KFilePlacesModel
/usr/include/KF6/KIOFileWidgets/KFilePlacesView
/usr/include/KF6/KIOFileWidgets/KFilePreviewGenerator
/usr/include/KF6/KIOFileWidgets/KFileWidget
/usr/include/KF6/KIOFileWidgets/KImageFilePreview
/usr/include/KF6/KIOFileWidgets/KNameAndUrlInputDialog
/usr/include/KF6/KIOFileWidgets/KNewFileMenu
/usr/include/KF6/KIOFileWidgets/KPreviewWidgetBase
/usr/include/KF6/KIOFileWidgets/KUrlNavigator
/usr/include/KF6/KIOFileWidgets/kabstractviewadapter.h
/usr/include/KF6/KIOFileWidgets/kdiroperator.h
/usr/include/KF6/KIOFileWidgets/kdirsortfilterproxymodel.h
/usr/include/KF6/KIOFileWidgets/kencodingfiledialog.h
/usr/include/KF6/KIOFileWidgets/kfilecopytomenu.h
/usr/include/KF6/KIOFileWidgets/kfilecustomdialog.h
/usr/include/KF6/KIOFileWidgets/kfilefiltercombo.h
/usr/include/KF6/KIOFileWidgets/kfileplaceeditdialog.h
/usr/include/KF6/KIOFileWidgets/kfileplacesmodel.h
/usr/include/KF6/KIOFileWidgets/kfileplacesview.h
/usr/include/KF6/KIOFileWidgets/kfilepreviewgenerator.h
/usr/include/KF6/KIOFileWidgets/kfilewidget.h
/usr/include/KF6/KIOFileWidgets/kimagefilepreview.h
/usr/include/KF6/KIOFileWidgets/kiofilewidgets_export.h
/usr/include/KF6/KIOFileWidgets/knameandurlinputdialog.h
/usr/include/KF6/KIOFileWidgets/knewfilemenu.h
/usr/include/KF6/KIOFileWidgets/kpreviewwidgetbase.h
/usr/include/KF6/KIOFileWidgets/kurlnavigator.h
/usr/include/KF6/KIOGui/KCoreUrlNavigator
/usr/include/KF6/KIOGui/KEMailClientLauncherJob
/usr/include/KF6/KIOGui/KIO/ApplicationLauncherJob
/usr/include/KF6/KIOGui/KIO/CommandLauncherJob
/usr/include/KF6/KIOGui/KIO/DndPopupMenuPlugin
/usr/include/KF6/KIOGui/KIO/FavIconRequestJob
/usr/include/KF6/KIOGui/KIO/OpenFileManagerWindowJob
/usr/include/KF6/KIOGui/KIO/OpenUrlJob
/usr/include/KF6/KIOGui/KIO/OpenWithHandlerInterface
/usr/include/KF6/KIOGui/KIO/PreviewJob
/usr/include/KF6/KIOGui/KIO/ThumbnailCreator
/usr/include/KF6/KIOGui/KTerminalLauncherJob
/usr/include/KF6/KIOGui/KUriFilter
/usr/include/KF6/KIOGui/kcoreurlnavigator.h
/usr/include/KF6/KIOGui/kemailclientlauncherjob.h
/usr/include/KF6/KIOGui/kio/applicationlauncherjob.h
/usr/include/KF6/KIOGui/kio/commandlauncherjob.h
/usr/include/KF6/KIOGui/kio/dndpopupmenuplugin.h
/usr/include/KF6/KIOGui/kio/faviconrequestjob.h
/usr/include/KF6/KIOGui/kio/openfilemanagerwindowjob.h
/usr/include/KF6/KIOGui/kio/openurljob.h
/usr/include/KF6/KIOGui/kio/openwithhandlerinterface.h
/usr/include/KF6/KIOGui/kio/previewjob.h
/usr/include/KF6/KIOGui/kio/thumbnailcreator.h
/usr/include/KF6/KIOGui/kiogui_export.h
/usr/include/KF6/KIOGui/kterminallauncherjob.h
/usr/include/KF6/KIOGui/kurifilter.h
/usr/include/KF6/KIOWidgets/KAbstractFileItemActionPlugin
/usr/include/KF6/KIOWidgets/KBuildSycocaProgressDialog
/usr/include/KF6/KIOWidgets/KDirLister
/usr/include/KF6/KIOWidgets/KDirModel
/usr/include/KF6/KIOWidgets/KFile
/usr/include/KF6/KIOWidgets/KFileItemActions
/usr/include/KF6/KIOWidgets/KFileItemDelegate
/usr/include/KF6/KIOWidgets/KIO/DeleteOrTrashJob
/usr/include/KF6/KIOWidgets/KIO/DropJob
/usr/include/KF6/KIOWidgets/KIO/FileUndoManager
/usr/include/KF6/KIOWidgets/KIO/JobUiDelegate
/usr/include/KF6/KIOWidgets/KIO/KUriFilterSearchProviderActions
/usr/include/KF6/KIOWidgets/KIO/Paste
/usr/include/KF6/KIOWidgets/KIO/PasteJob
/usr/include/KF6/KIOWidgets/KIO/RenameDialog
/usr/include/KF6/KIOWidgets/KIO/RenameFileDialog
/usr/include/KF6/KIOWidgets/KIO/SkipDialog
/usr/include/KF6/KIOWidgets/KIO/SslUi
/usr/include/KF6/KIOWidgets/KIO/WidgetsAskUserActionHandler
/usr/include/KF6/KIOWidgets/KOpenWithDialog
/usr/include/KF6/KIOWidgets/KPropertiesDialog
/usr/include/KF6/KIOWidgets/KPropertiesDialogPlugin
/usr/include/KF6/KIOWidgets/KShellCompletion
/usr/include/KF6/KIOWidgets/KSslCertificateBox
/usr/include/KF6/KIOWidgets/KSslInfoDialog
/usr/include/KF6/KIOWidgets/KUrlComboBox
/usr/include/KF6/KIOWidgets/KUrlCompletion
/usr/include/KF6/KIOWidgets/KUrlRequester
/usr/include/KF6/KIOWidgets/KUrlRequesterDialog
/usr/include/KF6/KIOWidgets/kabstractfileitemactionplugin.h
/usr/include/KF6/KIOWidgets/kbuildsycocaprogressdialog.h
/usr/include/KF6/KIOWidgets/kdirlister.h
/usr/include/KF6/KIOWidgets/kdirmodel.h
/usr/include/KF6/KIOWidgets/kfile.h
/usr/include/KF6/KIOWidgets/kfileitemactions.h
/usr/include/KF6/KIOWidgets/kfileitemdelegate.h
/usr/include/KF6/KIOWidgets/kio/deleteortrashjob.h
/usr/include/KF6/KIOWidgets/kio/dropjob.h
/usr/include/KF6/KIOWidgets/kio/fileundomanager.h
/usr/include/KF6/KIOWidgets/kio/jobuidelegate.h
/usr/include/KF6/KIOWidgets/kio/kurifiltersearchprovideractions.h
/usr/include/KF6/KIOWidgets/kio/paste.h
/usr/include/KF6/KIOWidgets/kio/pastejob.h
/usr/include/KF6/KIOWidgets/kio/renamedialog.h
/usr/include/KF6/KIOWidgets/kio/renamefiledialog.h
/usr/include/KF6/KIOWidgets/kio/skipdialog.h
/usr/include/KF6/KIOWidgets/kio/sslui.h
/usr/include/KF6/KIOWidgets/kio/widgetsaskuseractionhandler.h
/usr/include/KF6/KIOWidgets/kiowidgets_export.h
/usr/include/KF6/KIOWidgets/kopenwithdialog.h
/usr/include/KF6/KIOWidgets/kpropertiesdialog.h
/usr/include/KF6/KIOWidgets/kpropertiesdialogplugin.h
/usr/include/KF6/KIOWidgets/kshellcompletion.h
/usr/include/KF6/KIOWidgets/ksslcertificatebox.h
/usr/include/KF6/KIOWidgets/ksslinfodialog.h
/usr/include/KF6/KIOWidgets/kurlcombobox.h
/usr/include/KF6/KIOWidgets/kurlcompletion.h
/usr/include/KF6/KIOWidgets/kurlrequester.h
/usr/include/KF6/KIOWidgets/kurlrequesterdialog.h
/usr/lib64/cmake/KF6KIO/KF6KIOConfig.cmake
/usr/lib64/cmake/KF6KIO/KF6KIOConfigVersion.cmake
/usr/lib64/cmake/KF6KIO/KF6KIOTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6KIO/KF6KIOTargets.cmake
/usr/lib64/libKF6KIOCore.so
/usr/lib64/libKF6KIOFileWidgets.so
/usr/lib64/libKF6KIOGui.so
/usr/lib64/libKF6KIOWidgets.so
/usr/lib64/libkuriikwsfiltereng_private.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/data/index.docbook
/usr/share/doc/HTML/ca/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/file/index.docbook
/usr/share/doc/HTML/ca/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/ca/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/ca/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/help/index.docbook
/usr/share/doc/HTML/ca/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/http/index.docbook
/usr/share/doc/HTML/ca/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/data/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/file/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/help/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/http/index.docbook
/usr/share/doc/HTML/ca@valencia/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/de/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/data/index.docbook
/usr/share/doc/HTML/de/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/file/index.docbook
/usr/share/doc/HTML/de/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/de/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/de/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/help/index.docbook
/usr/share/doc/HTML/de/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/http/index.docbook
/usr/share/doc/HTML/de/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/en/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/data/index.docbook
/usr/share/doc/HTML/en/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/file/index.docbook
/usr/share/doc/HTML/en/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/en/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/en/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/help/index.docbook
/usr/share/doc/HTML/en/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/http/index.docbook
/usr/share/doc/HTML/en/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/es/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/data/index.docbook
/usr/share/doc/HTML/es/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/file/index.docbook
/usr/share/doc/HTML/es/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/es/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/es/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/help/index.docbook
/usr/share/doc/HTML/es/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/http/index.docbook
/usr/share/doc/HTML/es/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/et/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/data/index.docbook
/usr/share/doc/HTML/et/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/file/index.docbook
/usr/share/doc/HTML/et/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/et/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/help/index.docbook
/usr/share/doc/HTML/et/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/http/index.docbook
/usr/share/doc/HTML/et/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/fr/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/data/index.docbook
/usr/share/doc/HTML/fr/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/file/index.docbook
/usr/share/doc/HTML/fr/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/fr/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/fr/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/help/index.docbook
/usr/share/doc/HTML/fr/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/http/index.docbook
/usr/share/doc/HTML/fr/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/gl/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/file/index.docbook
/usr/share/doc/HTML/gl/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/gl/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/help/index.docbook
/usr/share/doc/HTML/gl/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/http/index.docbook
/usr/share/doc/HTML/gl/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/it/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/data/index.docbook
/usr/share/doc/HTML/it/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/file/index.docbook
/usr/share/doc/HTML/it/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/it/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/it/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/help/index.docbook
/usr/share/doc/HTML/it/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/http/index.docbook
/usr/share/doc/HTML/it/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/nl/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/data/index.docbook
/usr/share/doc/HTML/nl/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/file/index.docbook
/usr/share/doc/HTML/nl/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/nl/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/nl/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/help/index.docbook
/usr/share/doc/HTML/nl/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/http/index.docbook
/usr/share/doc/HTML/nl/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/pt/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/data/index.docbook
/usr/share/doc/HTML/pt/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/file/index.docbook
/usr/share/doc/HTML/pt/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/pt/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/pt/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/help/index.docbook
/usr/share/doc/HTML/pt/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/http/index.docbook
/usr/share/doc/HTML/pt/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/data/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/file/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/help/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/http/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/ru/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/data/index.docbook
/usr/share/doc/HTML/ru/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/file/index.docbook
/usr/share/doc/HTML/ru/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/ru/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/ru/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/help/index.docbook
/usr/share/doc/HTML/ru/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/http/index.docbook
/usr/share/doc/HTML/ru/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/sr/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/data/index.docbook
/usr/share/doc/HTML/sr/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/file/index.docbook
/usr/share/doc/HTML/sr/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/sr/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sr/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/help/index.docbook
/usr/share/doc/HTML/sr/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/http/index.docbook
/usr/share/doc/HTML/sr/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/data/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/file/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/help/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/http/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/sv/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/data/index.docbook
/usr/share/doc/HTML/sv/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/file/index.docbook
/usr/share/doc/HTML/sv/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/sv/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/sv/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/help/index.docbook
/usr/share/doc/HTML/sv/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/http/index.docbook
/usr/share/doc/HTML/sv/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/tr/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/data/index.docbook
/usr/share/doc/HTML/tr/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/file/index.docbook
/usr/share/doc/HTML/tr/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/tr/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/tr/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/help/index.docbook
/usr/share/doc/HTML/tr/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/http/index.docbook
/usr/share/doc/HTML/tr/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/webdav/index.docbook
/usr/share/doc/HTML/uk/kioworker6/data/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/data/index.docbook
/usr/share/doc/HTML/uk/kioworker6/file/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/file/index.docbook
/usr/share/doc/HTML/uk/kioworker6/ftp/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/ftp/index.docbook
/usr/share/doc/HTML/uk/kioworker6/help/documentationnotfound/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/help/documentationnotfound/index.docbook
/usr/share/doc/HTML/uk/kioworker6/help/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/help/index.docbook
/usr/share/doc/HTML/uk/kioworker6/http/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/http/index.docbook
/usr/share/doc/HTML/uk/kioworker6/webdav/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/webdav/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6KIOCore.so.6.4.1
/V3/usr/lib64/libKF6KIOFileWidgets.so.6.4.1
/V3/usr/lib64/libKF6KIOGui.so.6.4.1
/V3/usr/lib64/libKF6KIOWidgets.so.6.4.1
/V3/usr/lib64/qt6/plugins/designer/kio6widgets.so
/V3/usr/lib64/qt6/plugins/kf6/kded/remotenotifier.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_file.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_ftp.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_ghelp.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_help.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_http.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_remote.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_trash.so
/V3/usr/lib64/qt6/plugins/kf6/kiod/kioexecd.so
/V3/usr/lib64/qt6/plugins/kf6/kiod/kpasswdserver.so
/V3/usr/lib64/qt6/plugins/kf6/kiod/kssld.so
/V3/usr/lib64/qt6/plugins/kf6/urifilters/fixhosturifilter.so
/V3/usr/lib64/qt6/plugins/kf6/urifilters/kshorturifilter.so
/V3/usr/lib64/qt6/plugins/kf6/urifilters/kuriikwsfilter.so
/V3/usr/lib64/qt6/plugins/kf6/urifilters/kurisearchfilter.so
/V3/usr/lib64/qt6/plugins/kf6/urifilters/localdomainurifilter.so
/usr/lib64/libKF6KIOCore.so.6
/usr/lib64/libKF6KIOCore.so.6.4.1
/usr/lib64/libKF6KIOFileWidgets.so.6
/usr/lib64/libKF6KIOFileWidgets.so.6.4.1
/usr/lib64/libKF6KIOGui.so.6
/usr/lib64/libKF6KIOGui.so.6.4.1
/usr/lib64/libKF6KIOWidgets.so.6
/usr/lib64/libKF6KIOWidgets.so.6.4.1
/usr/lib64/qt6/plugins/designer/kio6widgets.so
/usr/lib64/qt6/plugins/kf6/kded/remotenotifier.so
/usr/lib64/qt6/plugins/kf6/kio/kio_file.so
/usr/lib64/qt6/plugins/kf6/kio/kio_ftp.so
/usr/lib64/qt6/plugins/kf6/kio/kio_ghelp.so
/usr/lib64/qt6/plugins/kf6/kio/kio_help.so
/usr/lib64/qt6/plugins/kf6/kio/kio_http.so
/usr/lib64/qt6/plugins/kf6/kio/kio_remote.so
/usr/lib64/qt6/plugins/kf6/kio/kio_trash.so
/usr/lib64/qt6/plugins/kf6/kiod/kioexecd.so
/usr/lib64/qt6/plugins/kf6/kiod/kpasswdserver.so
/usr/lib64/qt6/plugins/kf6/kiod/kssld.so
/usr/lib64/qt6/plugins/kf6/urifilters/fixhosturifilter.so
/usr/lib64/qt6/plugins/kf6/urifilters/kshorturifilter.so
/usr/lib64/qt6/plugins/kf6/urifilters/kuriikwsfilter.so
/usr/lib64/qt6/plugins/kf6/urifilters/kurisearchfilter.so
/usr/lib64/qt6/plugins/kf6/urifilters/localdomainurifilter.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kio/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kio/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kio/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/kio/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kio/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
/usr/share/package-licenses/kio/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/kio/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/kio/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kio/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/kio/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kio/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kio/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/kio/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f kio6.lang
%defattr(-,root,root,-)

